# Generated by Django 4.0.4 on 2022-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='projects/static/images/default.jpg', upload_to='projects/static/images/'),
        ),
    ]
