# Generated by Django 4.0.4 on 2022-04-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
