# Generated by Django 4.0.4 on 2022-04-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
