# Generated by Django 4.0.4 on 2022-05-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('projects', '0004_alter_image_image'),
    ]

    operations = [
    ]
