# Generated by Django 4.0.4 on 2022-05-04 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_alter_rating_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='RATING',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
