# Generated by Django 4.0.4 on 2022-05-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
