# Generated by Django 4.0.4 on 2022-05-14 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
        ('projects', '0002_initial'),
        ('reports', '0003_alter_report_related_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='related_comment',
        ),
        migrations.RemoveField(
            model_name='report',
            name='related_project',
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
                ('related_comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
            ],
            bases=('reports.report',),
        ),
    ]
