# Generated by Django 4.0.4 on 2022-05-15 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_related_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
    ]
